sudo: required
services:
  - docker

before_install:
  - docker build -t ynno/docker-react -f Dockerfile.dev .

script:
  - docker run ynno/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-534657018077"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  